### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by qwertymodo** [defparam/snes-exp-bridge#1]
Can you post the part numbers for the connectors used?  I know there's basically just 2 parts, so a full BOM is probably overkill, but mostly I'm trying to figure out what audio jack you're using.  The DB-25 connector is probably pretty standard, but audio barrel jacks come in all kinds of shapes, sizes, and footprints.

**Comment by defparam** [comment]
For EXP BOARD notable parts (digikey links):

TE Connectivity 1734350-1 - https://www.digikey.com/product-detail/en/te-connectivity-amp-connectors/1734350-1/A35111-ND/1279824
CUI Inc. SJ1-3535NG-GR - https://www.digikey.com/product-detail/en/cui-inc/SJ1-3535NG-GR/CP1-3535NG-GR-ND/2295993
CUI Inc. SJ1-3535NG-BE - https://www.digikey.com/product-detail/en/cui-inc/SJ1-3535NG-BE/CP1-3535NG-BE-ND/2295992

For 21FX Rev C notable parts (digikey links):

3M 8432-11B1-RK-TP - https://www.digikey.com/product-detail/en/3m/8432-11B1-RK-TP/3M3211B1-ND/1026472
Microchip SST39SF010A-70-4C-NHE - https://www.digikey.com/product-detail/en/microchip-technology/SST39SF010A-70-4C-NHE/SST39SF010A-70-4C-NHE-ND/2297825
Norcomp Inc. 182-025-113R531 - https://www.digikey.com/product-detail/en/norcomp-inc/182-025-113R531/182-25ME-ND/858361

The holes I used for the audio connectors are not slotted (because OSHPark doesn't do plated slots). So Those holes are really large however it still works for those parts. If you aren't using audio you can safely omit the audio connectors as they are fairly expensive. Since you are looking at 21FX I also put some parts I used above. FYI you need an external programmer to program byuu's IPLROM onto the microchip EEPROM. Lastly for the 21FX you need the adafruit FTDI board (yeahhh, 21FX needs a tech refresh, it was intended originally to not have USB).

**Comment by qwertymodo** [comment]
Perfect, thanks.

**Comment by defparam** [comment]
21FX (couple more parts I missed): 

CTS CB3-3I-40M0000 - https://www.digikey.com/product-detail/en/cts-frequency-controls/CB3-3I-40M0000/CTX314CT-ND/663676
Altera EPM7064STC44-10N - https://www.digikey.com/product-detail/en/altera/EPM7064STC44-10N/544-2020-ND/1084671
Adafruit 232H breakout - https://www.adafruit.com/products/2264?gclid=Cj0KEQjwpNm-BRCJ3rDNmOuKi9IBEiQAlzDJH5C-KYeJ1GzxMTDzVYMzVn6vXJsWXZp7LBVuTMgdP_0aAjwL8P8HAQ
